### ISSUE TITLE
get bug

### ISSUE THREAD

**Issue by Vpowgh** [pola/we-connect-id#1]
I think in get function there is indentation bug, now _session.get is always called twice.

Further, it is a good idea to use try-except with _session.get because if something happens during communication it will otherwise crash to exceptions.

```
    def get(self, endpoint):
        r = self._session.get(BASE_URL + endpoint)

        if r.status_code == 401:
            self._sign_in(True)

        r = self._session.get(BASE_URL + endpoint)

        return r.json()
```

**Comment by pola** [comment]
Thank you! I have fixed the indentation.
