### ISSUE TITLE
Status not working

### ISSUE THREAD

**Issue by Vpowgh** [pola/we-connect-id#3]
The endpoint '/status' used in example has been deprecated and does not work anymore (at least for me).

Instead endpoint '/selectivestatus?jobs=all' can be used to get overall status. 
This system provides also way to fetch one or multiple statuses selectively, for example to get charging and access status endpoint '/selectivestatus?jobs=access,charging' can be used.

**Comment by RoadRunnner** [comment]
Dear Vpowgh,
thank you for this comment.
I did not recive an data with the endpoint '/status' too since monday this week.
The endpoint '/selectivestatus?jobs=all' is woring fine now.
But from where do you have this information about the new endpoint?

**Comment by Vpowgh** [comment]
There are several repos in github for VW WeConnect so information is there.

For example:
https://github.com/tillsteinbach/WeConnect-python
https://github.com/skagmo/ha_vwid

**Comment by pola** [comment]
Thank you for the links to the other repositories, @Vpowgh.

I have updated `example.py` with the new status endpoint, @RoadRunnner. Please note that the structure of the output is slightly different compared to how it used to be.
